### ISSUE TITLE
gradle: weird OSGi tests failure

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#1175]
This is blocking me integrating OSGi tests in one of my projects.

I have added OSGi tests to my bndtoolsPlugins project, see branch 'tests' of https://github.com/fhuberts/bndtoolsPlugins

The tests run fine in Eclipse.

However, they do NOT run  with gradle (at least when NOT using the gradle daemon).

In that case, somehow biz.aQute.junit 3.0.0.201509101327 (0ac3b76c9bd573dfc30cbeaa53700c13ee5187d0) is used.
Where that bundle comes from is an utter mystery to me because it is nowhere in the workspace or in the used repositories.

It should use biz.aQute.junit from the latest build of bnd.

I've even blown away the caches (cnf/cache _and_ ~/.bnd) but that doesn't help.
It doesn't even matter if I git-clean the workspace before building.

It is reproducible with
```
./gradlew --no-daemon
```

**Comment by fhuberts** [comment]
The reason that this was exposed is that biz.aQute.junit 3.0.0.201509101327 (0ac3b76 / 3.0.0.REL) is BROKEN.

It exports hamcrest with the junit version.

**Comment by bjhargrave** [comment]
We made some changes post-3.0 (2b76881 and 6767e59) to use proper version numbers and subfolders in cnf/cache for the embedded repo contents. There were problems with bnd and bndtools fighting over the contents of the cnf/cache/*/*-latest.jar files. This also caused problems in the bnd junit tests where it was using the older version (-latest from cnf/cache) instead of the version just built (in the workspace repo).

biz,aQute.junit was also fixed in c156ced to not export the hamcrest packages with the junit version.

So I think all of this is fixed in master.

**Comment by bjhargrave** [comment]
Also, you can probably get your tests to run from gradle if you `git clean -dfx` first since that will wipe the cnf/cache folder clean removing whatever bndtools might have put there.

The basic lesson here is that putting -latest files in cnf/cache is a big no-no since they are not necessarily the latest versions from someones (bndtools or gradle) perspective.

**Comment by fhuberts** [comment]
On 30/10/15 18:44, BJ Hargrave wrote:
>
> We made some changes post-3.0 (2b76881 
> <https://github.com/bndtools/bnd/commit/2b7688149ad26769f9b7fa0086d2224b18cb02f7> 
> and 6767e59 
> <https://github.com/bndtools/bnd/commit/6767e59fed1e51bd1431d1b5e9f6eb3859b9b38a>) 
> to use proper version numbers and subfolders in cnf/cache for the 
> embedded repo contents. There were problems with bnd and bndtools 
> fighting over the contents of the cnf/cache////-latest.jar files. This 
> also caused problems in the bnd junit tests where it was using the 
> older version (-latest from cnf/cache) instead of the version just 
> built (in the workspace repo).
>
> biz,aQute.junit was also fixed in c156ced 
> <https://github.com/bndtools/bnd/commit/c156cedea198c926234167bbadb8e2bc0739d9da> 
> to not export the hamcrest packages with the junit version.
>
> So I think all of this is fixed in master.
>

I'll try that.

But can you answer where the heck the bundle is coming from?
It appears with git-cleaned workspace and blown-away caches...

**Comment by fhuberts** [comment]
On 30/10/15 18:50, BJ Hargrave wrote:
>
> Also, you can probably get your tests to run from gradle if you |git 
> clean -dfx| first since that will wipe the cnf/cache folder clean 
> removing whatever bndtools might have put there.
>
Have done so. As I explained

> The basic lesson here is that putting -latest files in cnf/cache is a 
> big no-no since they are not necessarily the latest versions from 
> someones (bndtools or gradle) perspective.
>

As I've said a long time ago.
And you also need to check checksums for when someone doesn't update the 
version.

**Comment by fhuberts** [comment]
On 30/10/15 18:55, Ferry Huberts wrote:
>>
>> So I think all of this is fixed in master.
>>
>
> I'll try that.

no difference
still doesn't work

**Comment by fhuberts** [comment]
BTW there is more going on, related to resolving in bndtools.
I was totally unable to resolve the bnd.bnd file for the test project and had to assemble the runbundles by hand.

**Comment by bjhargrave** [comment]
Well I can't build your tests branch anyway

```
[hargrave@macbookpro3 bndtoolsPlugins (tests)]$ ./gradlew --no-daemon

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/hargrave/git/tmp/bndtoolsPlugins/build/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':build'.
> Bnd property "Git-SHA" not found in project build

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.03 secs
```

**Comment by fhuberts** [comment]
you need to have a parallel checkout of bndtools (master)

**Comment by fhuberts** [comment]
Weird, now it works for me with the latest biz.aQute.bnd.gradle.jar
I _did_ try that earlier.
Can you please confirm that it works for you?
I've been struggling with this for a large part of the afternoon... :-(

**Comment by bjhargrave** [comment]
Then you need to provide way more information on how to reproduce. I checked out bndtools along side your repo checkout and built 3.0.0.REL. I then get the following error building your repo:

```
nl.pelagic.bndtools.headless.build.plugin.gradle:jar
Error  : The bundle version (3.0.0/3.0.0) is too low, must be at least 3.0.1
:nl.pelagic.bndtools.headless.build.plugin.gradle:jar FAILED
```

Please make a detailed and simple way to reproduce the problem. This is too much work to chase down how to reproduce your complex scenario.

**Comment by fhuberts** [comment]
bndtools master, my project also master

**Comment by bjhargrave** [comment]
```
:build:p2Landing
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/sapphire/releng/listing/GenFolderListingOp : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
:build:p2Landing FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/hargrave/git/tmp/bndtoolsPlugins/build/build.gradle' line: 115

* What went wrong:
Execution failed for task ':build:p2Landing'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```
I assume you do not use the same java 7 as bndtools? (sigh)

**Comment by fhuberts** [comment]
But the tests did run successfully then?
If so then you can close this.

Guess the 3.0.0.REL junit bundle is quite broken then.

And it's still a mystery where the 3.0.0.REL junit bundle was coming from.

**Comment by bjhargrave** [comment]
Well everything before that failure worked. But I am using your master branch as you said to recently above, not the tests branch that you mentioned in your initial comment.

**Comment by fhuberts** [comment]
THat was a typo. It should be the tests branch. sorry

**Comment by fhuberts** [comment]
a ```gradle build``` avoid the p2 stuff

**Comment by bjhargrave** [comment]
`:nl.pelagic.bndtools.headless.build.plugin.gradle.test:check FAILED` on tests branch using Java 8.

**Comment by fhuberts** [comment]
So now we have the wonderful situation that the tables have turned: it works for me but not for you.
A nice WTF.

**Comment by fhuberts** [comment]
Ah, but I upgrade the gradle dependencies to the latest bnd build bundles.
That is the difference now. You can try that

**Comment by fhuberts** [comment]
It fails for me on the tests branch as well. Reproducable.
The current master branch succeeds, that has upgraded gradle deps.

**Comment by bjhargrave** [comment]
There is no update in tests branch that I see.

**Comment by fhuberts** [comment]
correct. master was updated. basically master == tests + upgraded gradle deps

**Comment by bjhargrave** [comment]
So it works now. Closing this issue.

**Comment by fhuberts** [comment]
Well the root cause is not fixed.
3.0.0.REL junit is broken.
And something else too: where the heck did the 3.0.0 junit bundle come from? Who downloaded it because it is not in the used repos

**Comment by bjhargrave** [comment]
Yes, 3.0.0.REL is messed up. Fixed for 3.1. What else?

**Comment by fhuberts** [comment]
When can we expect 3.1?
I prefer sticking with stable releases but this forces me on master

**Comment by bjhargrave** [comment]
I don't have a time frame. I know we don't want to wait as long as between 2.4 and 3.0. But right now people are busy for EclipseCon, etc.
