### ISSUE TITLE
bnd-indexer-maven creates wrong osgi.ee requirement

### ISSUE THREAD

**Issue by Sandared** [bndtools/bnd#3706]
Hi,

I created a new application with the enroute project archetype, packaged the impl project and then tried to index and resolve the application. During resolving the bnd-resolver-maven plugin complains about not being able to satisfy the execution environment requirement of my application:

```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=io.qbilon.impl)
          ⇒ [io.qbilon.impl version=1.0.0.201912201330]
              ⇒ osgi.ee: (&(osgi.ee=JavaSE)(version=11))
```

I assume this stems from the index where my implementation is said to need Java 11
```xml
<resource>
    ...
    <requirement namespace="osgi.ee">
      <directive name="filter" value="(&amp;(osgi.ee=JavaSE)(version=11))"/>
    </requirement>
  </resource>
```

However, in my bndrun file I state to use Java 8:
```
-runee: JavaSE-1.8
```
and in the parent POM I also set Java 8:
```xml
<properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <bnd.version>4.3.0</bnd.version>
</properties>
```
The installed Java version on my PC is 
```
java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```
And also the Manifest of the generated impl.jar says it need Java 8:
```
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.compo
 nent)(version>=1.4.0)(!(version>=2.0.0)))",osgi.ee;filter:="(&(osgi.e
 e=JavaSE)(version=1.8))"
```

I'm not sure what I'm doing wrong or if this is a bug in the bnd-indexer-maven plugin.
Can you please help me?

Kind regards,
Thomas

**Comment by bjhargrave** [comment]
Can you please provide a small github repo which demonstrates the problem? Then we can investigate. Thanks.

**Comment by Sandared** [comment]
Of course: https://github.com/Sandared/bnd-indexer-bug
However, this is only the enroute project archetype. 
After building the impl and resolving the app I get this error.

**Comment by bjhargrave** [comment]
There are no directions in the small github repo on how to reproduce the bug.

**Comment by Sandared** [comment]
I die the following steps:
Froom project root
* cd impl
* mvn install
* cd ..
* mvn -pl app -am bnd-indexer:index bnd-indexer:index@test-index
bnd-resolver:resolve

And then I get the above mentioned error.

BJ Hargrave <notifications@github.com> schrieb am Di., 7. Jan. 2020, 18:05:

**Comment by bjhargrave** [comment]
I did the following steps:

```shell
git clone https://github.com/Sandared/bnd-indexer-bug 
cd bnd-indexer-bug 
cd impl
mvn -Dmaven.repo.local=../target/m2 --no-transfer-progress install
cd ..
mvn -Dmaven.repo.local=target/m2 --no-transfer-progress -pl app -am bnd-indexer:index bnd-indexer:index@test-index bnd-resolver:resolve
```

Note: I specified a new local m2 repo cache to avoid any pollution issues with the default `~/.m2/repository` cache.

The build was successful for me:

```shell
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] bnd-indexer-bug                                                    [pom]
[INFO] impl                                                               [jar]
[INFO] app                                                                [jar]
[INFO] 
[INFO] ---------------------< io.jatoms:bnd-indexer-bug >----------------------
[INFO] Building bnd-indexer-bug 1.0-SNAPSHOT                              [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- bnd-indexer-maven-plugin:4.1.0:index (default-cli) @ bnd-indexer-bug ---
[INFO] 
[INFO] --- bnd-indexer-maven-plugin:4.1.0:index (test-index) @ bnd-indexer-bug ---
[INFO] 
[INFO] --- bnd-resolver-maven-plugin:4.1.0:resolve (default-cli) @ bnd-indexer-bug ---
[INFO] 
[INFO] ---------------------------< io.jatoms:impl >---------------------------
[INFO] Building impl 1.0-SNAPSHOT                                         [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- bnd-indexer-maven-plugin:4.1.0:index (default-cli) @ impl ---
[INFO] 
[INFO] --- bnd-indexer-maven-plugin:4.1.0:index (test-index) @ impl ---
[INFO] 
[INFO] --- bnd-resolver-maven-plugin:4.1.0:resolve (default-cli) @ impl ---
[INFO] 
[INFO] ---------------------------< io.jatoms:app >----------------------------
[INFO] Building app 1.0-SNAPSHOT                                          [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- bnd-indexer-maven-plugin:4.1.0:index (default-cli) @ app ---
[INFO] 
[INFO] --- bnd-indexer-maven-plugin:4.1.0:index (test-index) @ app ---
[INFO] 
[INFO] --- bnd-resolver-maven-plugin:4.1.0:resolve (default-cli) @ app ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for bnd-indexer-bug 1.0-SNAPSHOT:
[INFO] 
[INFO] bnd-indexer-bug .................................... SUCCESS [  0.759 s]
[INFO] impl ............................................... SUCCESS [  0.357 s]
[INFO] app ................................................ SUCCESS [ 12.250 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.686 s
[INFO] Finished at: 2020-01-27T10:22:28-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by bjhargrave** [comment]
I will also note you are using a quite old version of the Bnd maven plugins. We have just released 5.0.0.

**Comment by bjhargrave** [comment]
The generated index information for the impl shows:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<repository xmlns="http://www.osgi.org/xmlns/repository/v1.0.0" name="app" increment="1580138547500">
  <resource>
    <capability namespace="osgi.identity">
      <attribute name="osgi.identity" value="io.jatoms.impl"/>
      <attribute name="type" value="osgi.bundle"/>
      <attribute name="version" value="1.0.0.202001271521" type="Version"/>
    </capability>
    <capability namespace="osgi.wiring.bundle">
      <attribute name="bundle-version" value="1.0.0.202001271521" type="Version"/>
      <attribute name="osgi.wiring.bundle" value="io.jatoms.impl"/>
    </capability>
    <capability namespace="osgi.wiring.host">
      <attribute name="bundle-version" value="1.0.0.202001271521" type="Version"/>
      <attribute name="osgi.wiring.host" value="io.jatoms.impl"/>
    </capability>
    <capability namespace="osgi.content">
      <attribute name="size" value="4694" type="Long"/>
      <attribute name="url" value="file:/Users/hargrave/git/tmp/bnd-indexer-bug/target/m2/io/jatoms/impl/1.0-SNAPSHOT/impl-1.0-SNAPSHOT.jar"/>
      <attribute name="mime" value="application/vnd.osgi.bundle"/>
      <attribute name="osgi.content" value="8E54DC5FEC5873D7F89893D5A88BE161E8E827383DD1BD7DDD4C2B21E439A5E8"/>
    </capability>
    <requirement namespace="osgi.extender">
      <directive name="filter" value="(&amp;(osgi.extender=osgi.component)(version&gt;=1.4.0)(!(version&gt;=2.0.0)))"/>
    </requirement>
    <requirement namespace="osgi.ee">
      <directive name="filter" value="(&amp;(osgi.ee=JavaSE)(version=1.8))"/>
    </requirement>
  </resource>
```

which has the correct `osgi.ee` requirement.

**Comment by Sandared** [comment]
Hi @bjhargrave  thanks for looking into this. 
I didn't know that there is already a 5.0.0 version of the bnd-maven plugins.
I've set up a completely new workspace with the new plugins and now it works.

Maybe in my old workspace something was cached wrong or I made some stupid mistake that I'm still not aware of. However, as this works now I will proceed with the working version :)

Thanks for your help!
