### ISSUE TITLE
Workspace Fragment is not loading bundles from `*.pmvn`

### ISSUE THREAD

**Issue by peterkir** [bndtools/bnd#6907]
When adding Workspace Fragment `org.bndtools.demo.webapp` the MavenBndRepo is created, but it is not downloading the GAV artifacts.
Copying the GAVs into the `runtime.mvn` is downloading them and then also the `.pmvn` is working.

<img width="659" height="632" alt="Image" src="https://github.com/user-attachments/assets/e82373e2-c744-4ae7-9d2b-5005fa971a14" />

Breakpoint on  `aQute.bnd.repository.maven.provider.MavenBndRepository.get(String, Version, Map<String, String>, DownloadListener...)` is not called for the bundles from `*.pmvn` file. The repo is listed in the workspace and also the httpclient is visible for the pmvn repo.

@pkriens Any idea what the `aQute.bnd.build.MagicBnd.convertMaven(Workspace, File)` could be missing in adding the repo to the workspace?

**Comment by chrisrueger** [comment]
I think I found something: 2 Things:

1. pmvn file incorrect

The file needs to start with the key = value pairs immediately, otherwise they are not parsed

Correct: 

```

# name = org.bndtools.templates.osgi-servlet
# releaseUrl = https://repo.maven.apache.org/maven2/
# snapshotUrl = https://oss.sonatype.org/content/repositories/snapshots/

org.slf4j:slf4j-api:1.7.0
org.slf4j:slf4j-simple:1.7.1
```

wrong:
```
SOMETHING ELSE BEFORE
# name = org.bndtools.templates.osgi-servlet
# releaseUrl = https://repo.maven.apache.org/maven2/
# snapshotUrl = https://oss.sonatype.org/content/repositories/snapshots/

org.slf4j:slf4j-api:1.7.0
org.slf4j:slf4j-simple:1.7.1
```

2. the concatenation of the pairs adds an extra single quote 


<img width="2482" height="848" alt="Image" src="https://github.com/user-attachments/assets/94a64e23-eddf-4fd2-ae78-7daacf6313e0" />

which results in a wrong url 

<img width="2730" height="1114" alt="Image" src="https://github.com/user-attachments/assets/1d327f3c-876e-4f1d-9923-eb4c4f524444" />


I will have a look later

**Comment by peterkir** [comment]
thx. You were absolutely right. I have fixed the template and removed the superfluos slf4j.nop bundle and update to the latest 1.7.36 version.

**Comment by chrisrueger** [comment]
What about 2) the additional quote which makes the URL wrong? Is that not an issue anymore?

**Comment by peterkir** [comment]
Hmm I will check...

**Comment by chrisrueger** [comment]
Still an issue. Fixing it right now: https://github.com/bndtools/bnd/pull/6908

**Comment by chrisrueger** [comment]
PR merged. Should work now again. Just try changing the slf4j version in the `.pmvn` to a one which you don't have locally. It should download it now
