### ISSUE TITLE
bnd tracing is spamming my syslog

### ISSUE THREAD

**Issue by fhuberts** [bndtools/bnd#806]
bnd - through  Eclipse - is spamming my syslog.
its build logging is sent to the syslog by Eclipse.

IMHO build logging should only be performed when so configured, not by default.

**Comment by fhuberts** [comment]
Please tell me how to turn off 'trace'. the messages are completely obfuscating syslog I _need_ to see.
I tried '-trace: false' but that doesn't work.

**Comment by njbartlett** [comment]
Are you saying that setting "Build Debug Logging" to "None" still produces logging output?

Also, why the hell is Eclipse sending this to syslog...?

**Comment by fhuberts** [comment]
On 17/02/15 21:30, Neil Bartlett wrote:
>
> Are you saying that setting "Build Debug Logging" to "None" still 
> produces logging output?
>

Yes

> Also, why the hell is Eclipse sending this to syslog...?
>

Because bnd does 'System.err.println()' in its trace methods, and 
tracing is enabled by default apparently.

# grep -nr System.err|grep '#'
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java:731: 
System.err.printf("# " + msg + "%n", parms);

**Comment by njbartlett** [comment]
Okay... tracing is different from the Build Debug logging, and I've no idea why that would be turned on.

**Comment by fhuberts** [comment]
I think I just found it, it's in bndtools.

On the next branch, line 640 in NewBuilder: 
```
            model.setTrace(true);
```

Unfortunately bndtools-next (_and_ bnd-next) doesn't build for me because everything builds with latest bnd, which apparently is not compatible, so I can't provide a PR.

Can you please change that line to:
```
            model.setTrace(false);
```

and then release a bndtools 2.4.2.REL?

**Comment by fhuberts** [comment]
(either not compatible or not compatible with my Java 8)

**Comment by bjhargrave** [comment]
You must compile with JDK 7.

Use
`./gradlew -Pbnd_repourl=https://bndtools.ci.cloudbees.com/job/bnd.next/lastSuccessfulBuild/artifact/dist/bundles --continue` to build against the bnd.next artifacts.

**Comment by fhuberts** [comment]
Fedora 21 only has Java 8, so I can't provide a PR.

**Comment by bjhargrave** [comment]
Also, I don't think there are any plans for another 2.4 release.

**Comment by fhuberts** [comment]
So that means I'm stuck with the spamming and have to wait a long time until v3?

**Comment by bjhargrave** [comment]
Unless you build your desired fix yourself. I imagine you can figure that out.

**Comment by fhuberts** [comment]
Why so reluctant with bugfix releases?
A lot of people only use the released version (by choice or by policy) and a bug fix release is not a lot of work.
Besides, fixes can be cherry-picked over from one branch to another.
The general idea of building a community is to make it easy for people to fix stuff and to release fixes promptly so that people (and the project!) can profit from fixing stuff.

**Comment by njbartlett** [comment]
I'd be happy to see this and a few other fixes go into a bugfix release for 2.4.

**Comment by fhuberts** [comment]
Thanks Neil

**Comment by pkriens** [comment]
Fixed in the latest release. The trace is no longer there

**Comment by fhuberts** [comment]
Is there a 2.4.2 release now?
It is still present on 2.4.1

**Comment by pkriens** [comment]
No 2.4.2 is planned.

**Comment by fhuberts** [comment]
Then it's not fixed.
3.0.0 is not released.
And as Neil said, he'd like a 2.4.2 release
